version: "3.8"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - freightmatic-network

networks:
  freightmatic-network:
    driver: bridge